modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ming_xt"
version="1.0.6.7"
displayName="Ming_xtçš„å¿«ä¹æ¨¡ç»„"
displayURL="https://space.bilibili.com/3493143982901884"
logoFile="logo.png"
credits="æ˜å°å¤©ğŸ‚ğŸº ç”±Bç«™UPxå°Oé½xä¸ºå…¶åˆ¶ä½œï¼Œä¸»é¡µï¼šhttps://space.bilibili.com/3493143982901884 Bç«™UPæ˜å°å¤©ä¸æ˜¯çŒ« ä¸»é¡µï¼šhttps://space.bilibili.com/694306843"
authors="Xiao_AwA_qi , Ming_xt"
description="æ˜å°å¤©ğŸ‚ğŸº"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ming_xt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration